global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    region: 'wh'
    replica: '0'

rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:8890']

  - job_name: 'master-scrape'
    metrics_path: '/metrics'
    params:
      format: [prometheus]
    honor_labels: true
    metric_relabel_configs:
      - regex: instance
        action: labeldrop
    file_sd_configs:
      - files:
          - targets.json



  - job_name: c-HG37znuc-kubernetes-cadvisor
    scheme: https
    bearer_token_file: token/c-HG37znuc.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.114.73:6443
        role: node
        bearer_token_file: token/c-HG37znuc.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.114.73:6443
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-HG37znuc
        target_label: clusterID
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        action: replace

  - job_name: c-HG37znuc-kubernetes-nodes
    scheme: https
    bearer_token_file: token/c-HG37znuc.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.114.73:6443
        role: node
        bearer_token_file: token/c-HG37znuc.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.114.73:6443
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-HG37znuc
        target_label: clusterID
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
        action: replace

  - job_name: c-HG37znuc-kubernetes-service-endpoints
    scheme: https
    bearer_token_file: token/c-HG37znuc.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.114.73:6443
        role: endpoints
        bearer_token_file: token/c-HG37znuc.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        separator: ;
        regex: "true"
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        separator: ;
        regex: (https?)
        target_label: __scheme__
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-HG37znuc
        target_label: clusterID
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.114.73:6443
        action: replace
      - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_endpoints_name,__meta_kubernetes_service_annotation_prometheus_io_port]
        separator: ;
        regex: (.+);(.+);(.*)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/${1}/services/${2}:${3}/proxy/metrics
        action: replace
      - separator: ;
        regex: __meta_kubernetes_service_label_(.+)
        replacement: $1
        action: labelmap
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: kubernetes_namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_name
        replacement: $1
        action: replace



  - job_name: c-G1xHVa0b-kubernetes-cadvisor
    scheme: https
    bearer_token_file: token/c-G1xHVa0b.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.114.57:6443
        role: node
        bearer_token_file: token/c-G1xHVa0b.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.114.57:6443
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-G1xHVa0b
        target_label: clusterID
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        action: replace

  - job_name: c-G1xHVa0b-kubernetes-nodes
    scheme: https
    bearer_token_file: token/c-G1xHVa0b.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.114.57:6443
        role: node
        bearer_token_file: token/c-G1xHVa0b.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.114.57:6443
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-G1xHVa0b
        target_label: clusterID
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
        action: replace

  - job_name: c-G1xHVa0b-kubernetes-service-endpoints
    scheme: https
    bearer_token_file: token/c-G1xHVa0b.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.114.57:6443
        role: endpoints
        bearer_token_file: token/c-G1xHVa0b.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        separator: ;
        regex: "true"
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        separator: ;
        regex: (https?)
        target_label: __scheme__
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-G1xHVa0b
        target_label: clusterID
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.114.57:6443
        action: replace
      - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_endpoints_name,__meta_kubernetes_service_annotation_prometheus_io_port]
        separator: ;
        regex: (.+);(.+);(.*)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/${1}/services/${2}:${3}/proxy/metrics
        action: replace
      - separator: ;
        regex: __meta_kubernetes_service_label_(.+)
        replacement: $1
        action: labelmap
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: kubernetes_namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_name
        replacement: $1
        action: replace



  - job_name: c-v6Uy9x2f-kubernetes-cadvisor
    scheme: https
    bearer_token_file: token/c-v6Uy9x2f.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.115.52:6443
        role: node
        bearer_token_file: token/c-v6Uy9x2f.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.115.52:6443
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-v6Uy9x2f
        target_label: clusterID
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        action: replace

  - job_name: c-v6Uy9x2f-kubernetes-nodes
    scheme: https
    bearer_token_file: token/c-v6Uy9x2f.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.115.52:6443
        role: node
        bearer_token_file: token/c-v6Uy9x2f.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.115.52:6443
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-v6Uy9x2f
        target_label: clusterID
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
        action: replace

  - job_name: c-v6Uy9x2f-kubernetes-service-endpoints
    scheme: https
    bearer_token_file: token/c-v6Uy9x2f.token
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - api_server: https://100.66.115.52:6443
        role: endpoints
        bearer_token_file: token/c-v6Uy9x2f.token
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        separator: ;
        regex: "true"
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        separator: ;
        regex: (https?)
        target_label: __scheme__
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region]
        action: replace
        replacement: c-v6Uy9x2f
        target_label: clusterID
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 100.66.115.52:6443
        action: replace
      - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_endpoints_name,__meta_kubernetes_service_annotation_prometheus_io_port]
        separator: ;
        regex: (.+);(.+);(.*)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/${1}/services/${2}:${3}/proxy/metrics
        action: replace
      - separator: ;
        regex: __meta_kubernetes_service_label_(.+)
        replacement: $1
        action: labelmap
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: kubernetes_namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_name
        replacement: $1
        action: replace